services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imobiliaria
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    command: >
      sh -c "sleep 20 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db


  pgadmin:
    image: dpage/pgadmin4:latest # Imagem oficial do pgAdmin 4
    environment:
      # Credenciais para acessar a interface web do pgAdmin
      PGADMIN_DEFAULT_EMAIL: admin@imobiliaria.com
      PGADMIN_DEFAULT_PASSWORD: admin_password_pg
    ports:
      - "5050:80" # Mapeia a porta 5050 do seu host para a porta 80 do container do pgAdmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db # Garante que o banco de dados suba antes do pgAdmin

volumes:
  pgdata:

  pgadmin-data:
